alphabets = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u',
             'v', 'w', 'x', 'y', 'z']

movie_names = [
    "Uri: The Surgical Strike",
    "Rangeela Raja",
    "Battalion 609",
    "The Accidental Prime Minister",
    "Why Cheat India",
    "Evening Shadows",
    "Soni",
    "Fraud Saiyaan",
    "Bombairiya",
    "Manikarnika: The Queen of Jhansi",
    "Thackeray",
    "Amavas",
    "Gully Boy",
    "Hum Chaar",
    "Total Dhamaal",
    "Sonchiriya",
    "Badla",
    "Mard Ko Dard Nahi Hota",
    "Hamid",
    "Photograph",
    "Risknamaa",
    "Mere Pyare Prime Minister",
    "22 Yards",
    "Kesari",
    "Notebook",
    "Junglee",
    "Gone Kesh",
    "Albert Pinto Ko Gussa Kyun Aata Hai?",
    "The Tashkent Files",
    "Kalank",
    "Setters",
    "Student of the Year 2",
    "PM Narendra Modi",
    "De De Pyaar De",
    "India's Most Wanted",
    "Yeh Hai India",
    "Khamoshi",
    "Kissebaaz",
    "Kabir Singh",
    "Article 15",
    "One Day: Justice Delivered",
    "Hume Tumse Pyaar Kitna",
    "Super 30",
    "Family of Thakurganj",
    "Batla House",
    "Jhootha Kahin Ka",
    "Judgementall Hai Kya",
    "Chicken Curry Law",
    "Arjun Patiala",
    "Jabariya Jodi",
    "Pranaam",
    "The Sky Is Pink",
    "Mission Mangal",
    "Saaho",
    "Dream Girl",
    "Section 375",
    "The Zoya Factor",
    "Pal Pal Dil Ke Paas",
    "Prassthanam",
    "P Se Pyaar F Se Faraar",
    "Ghost",
    "Bala",
    "Laal Kaptaan",
    "Yaaram",
    "Housefull 4",
    "Saand Ki Aankh",
    "Made in China",
    "Ujda Chaman",
    "Bypass Road",
    "Satellite Shankar",
    "Jhalki",
    "Marjaavaan",
    "Motichoor Chaknachoor",
    "Keep Safe Distance",
    "Pagalpanti",
    "Ramprasad Ki Tehrvi",
    "Yeh Saali Aashiqui",
    "Dil Bechara",
    "Pati Patni Aur Woh",
    "Commando 3",
    "Mardaani 2",
    "Dabangg 3",
    "Good Newwz",
    "Kaalakaandi",
    "Vodka Diaries",
    "My Birthday Song",
    "Nirdosh",
    "Mukkabaaz",
    "Union Leader",
    "Love per Square Foot",
    "Aiyaary",
    "Padmaavat",
    "Kuchh Bheege Alfaaz",
    "Jaane Kyun De Yaaron",
    "Veerey Ki Wedding",
    "Sonu Ke Titu Ki Sweety",
    "Hate Story 4",
    "Dil Juunglee",
    "3 Storeys",
    "Raid",
    "Hichki",
    "Missing",
    "Baaghi 2",
    "October",
    "Mercury",
    "Beyond the Clouds",
    "Nanu Ki Jaanu",
    "Daas Dev",
    "Omerta",
    "Raazi",
    "Hope Aur Hum",
    "High Jack",
    "Khajoor Pe Atke",
    "Parmanu: The Story of Pokhran",
    "Bioscopewala",
    "Bhavesh Joshi Superhero",
    "Phamous",
    "Race 3",
    "Dhadak",
    "Sanju",
    "Saheb Biwi Aur Gangster 3",
    "Nawabzaade",
    "Mulk",
    "Brij Mohan Amar Rahe",
    "Tikli and Laxmi Bomb",
    "Karwaan",
    "Gold",
    "Satyameva Jayate",
    "Happy Phirr Bhag Jayegi",
    "Genius",
    "Yamla Pagla Deewana: Phir Se",
    "Stree",
    "Paltan",
    "Laila Majnu",
    "Gali Guleiyan",
    "Halkaa",
    "Pataakha",
    "Batti Gul Meter Chalu",
    "Love Sonia",
    "Manto",
    "Ishqeria",
    "Manmarziyaan",
    "Mitron",
    "Sui Dhaaga",
    "Baazaar",
    "Jalebi",
    "FryDay",
    "Tumbbad",
    "Helicopter Eela",
    "Namaste England",
    "Andhadhun",
    "Badhaai Ho",
    "5 Weddings",
    "Kaashi in Search of Ganga",
    "Dassehra",
    "The Journey of Karma",
    "Jack and Dil",
    "Mohalla Assi",
    "Pihu",
    "Bhaiaji Superhit",
    "Hotel Milan",
    "Rajma Chawal",
    "Zero",
    "Simmba",
    "Tiger Zinda Hai",
    "Golmaal Again",
    "Judwaa 2",
    "Ok Jaanu",
    "Coffee with D",
    "Kaabil",
    "Raees",
    "Thugs of Hindostan",
    "Hind Ka Napak Ko Jawab: MSG Lion Heart 2",
    "Running Shaadi",
    "The Ghazi Attack",
    "Irada",
    "Rangoon",
    "Wedding Anniversary",
    "Mona Darling",
    "Jeena Isi Ka Naam Hai",
    "Badrinath Ki Dulhania",
    "Trapped",
    "Aa Gaya Hero",
    "Mantra",
    "Phillauri",
    "Machine",
    "Bhanwarey",
    "Anaarkali of Aarah",
    "Poorna: Courage Has No Limit",
    "Naam Shabana",
    "Mirza Juuliet",
    "Hotel Salvation",
    "Begum Jaan",
    "Noor",
    "Ek Thi Rani Aisi Bhi",
    "Maatr",
    "Sarkar 3",
    "Jattu Engineer",
    "Half Girlfriend",
    "Meri Pyaari Bindu",
    "Sachin: A Billion Dreams",
    "Hindi Medium",
    "Thodi Thodi Si Manmaaniyan",
    "Sweetiee Weds NRI",
    "Dobaara: See Your Evil",
    "Hanuman: Da' Damdaar",
    "Flat 211",
    "Dear Maya",
    "Raabta",
    "Behen Hogi Teri",
    "Tubelight",
    "Bank Chor",
    "Ek Haseena Thi Ek Deewana Tha",
    "Jagga Jasoos",
    "Shab",
    "Lipstick Under My Burkha",
    "Bachche Kachche Sachche",
    "G Kutta Se",
    "Indu Sarkar",
    "Jab Harry Met Sejal",
    "Munna Michael",
    "Toilet: Ek Prem Katha",
    "Mubarakan",
    "Guest iin London",
    "Bareilly Ki Barfi",
    "Babumoshai Bandookbaaz",
    "Yadvi – The Dignified Princess",
    "Qaidi Band",
    "Shubh Mangal Saavdhan",
    "Raag Desh",
    "Daddy",
    "Simran",
    "Lucknow Central",
    "A Gentleman",
    "Viceroy's House",
    "Patel Ki Punjabi Shaadi",
    "Newton",
    "The Final Exit",
    "Bhoomi",
    "Haseena Parkar",
    "JD",
    "Haraamkhor",
    "Poster Boys",
    "Mom",
    "Chef",
    "Ranchi Diaries",
    "Babuji Ek Ticket Bambai",
    "Rukh",
    "Secret Superstar",
    "Main Page",
    "Aval",
    "Ribbon",
    "Shaadi Mein Zaroor Aana",
    "Jia Aur Jia",
    "Qarib Qarib Singlle",
    "Aksar 2",
    "Panchlait",
    "Tumhari Sulu",
    "Julie 2",
    "Kadvi Hawa",
    "Firangi",
    "Fukrey Returns",
    "Monsoon Shootout",
    "Ajji",
    "Wazir",
    "Chalk n Duster",
    "Rebellious Flower",
    "Saankal",
    "Airlift",
    "Sallu Ki Shaadi",
    "Irudhi Suttru",
    "Kyaa Kool Hain Hum 3",
    "Mastizaade",
    "Dil Jo Na Keh Saka",
    "Jugni",
    "Ghayal: Once Again",
    "Fitoor",
    "Sanam Re",
    "Direct Ishq",
    "Ishq Forever",
    "Loveshhuda",
    "Neerja",
    "Aligarh",
    "Bollywood Diaries",
    "Love Shagun",
    "Tere Bin Laden: Dead or Alive",
    "Jai Gangaajal",
    "Teraa Surroor",
    "Kapoor & Sons",
    "Rocky Handsome",
    "Love Games",
    "Fan",
    "Nil Battey Sannata",
    "Laal Rang",
    "Baaghi",
    "Global Baba",
    "OK Mein Dhokhe",
    "Shortcut Safari",
    "The Blueberry Hunt",
    "Santa Banta Pvt Ltd",
    "Traffic",
    "1920: London",
    "Azhar",
    "Buddha in a Traffic Jam",
    "Murari the Mad Gentleman",
    "Dear Dad",
    "Phobia",
    "Sarbjit",
    "Veerappan",
    "Do Lafzon Ki Kahani",
    "Te3n",
    "Udta Punjab",
    "Khel Toh Ab Shuru Hoga",
    "Luv U Alia",
    "7 Hours to Go",
    "Raman Raghav 2.0",
    "Junooniyat",
    "Kaptaan",
    "Rough Book",
    "Dhanak",
    "Fredrick",
    "Dil Toh Deewana Hai",
    "Sultan",
    "Brahman Naman",
    "Great Grand Masti",
    "Waiting",
    "Ishq Click",
    "M Cream",
    "Madaari",
    "Dishoom",
    "Fever",
    "Rustom",
    "Hai Apna Dil Toh Awara",
    "Mohenjo Daro",
    "Happy Bhag Jayegi",
    "Waarrior Savitri",
    "Yea Toh Two Much Ho Gayaa",
    "A Flying Jatt",
    "Baar Baar Dekho",
    "Freaky Ali",
    "Raaz: Reboot",
    "Pink",
    "Parched",
    "Banjo",
    "Days of Tafree",
    "Wah Taj",
    "Island City",
    "Ek Kahani Julie Ki",
    "M.S. Dhoni: The Untold Story",
    "MSG: The Warrior Lion Heart",
    "Devi",
    "Motu Patlu: King of Kings",
    "Anna",
    "Fuddu",
    "Saat Uchakkey",
    "Beiimaan Love",
    "Ek Tera Saath",
    "Umrika",
    "Shivaay",
    "Dongari Ka Raja",
    "Ae Dil Hai Mushkil",
    "Tum Bin II",
    "Ishq Junoon",
    "Rock On 2",
    "Force 2",
    "Dear Zindagi",
    "Befikre",
    "Moh Maya Money",
    "Shorgul",
    "Saansein",
    "Ki & Ka",
    "Wajah Tum Ho",
    "Dangal",
    "Mirzya",
    "Prem Ratan Dhan Payo",
    "Tanu Weds Manu: Returns",
    "31st October",
    "ABCD 2",
    "Dilwale",
    "Bajrangi Bhaijaan",
    "Bajirao Mastani",
    "Welcome Back",
    "Baby",
    "Singh Is Bliing",
    "Gabbar Is Back",
    "Mumbai Can Dance Saala",
    "International Hero",
    "Alone",
    "Tevar",
    "Sharafat Gayi Tel Lene",
    "Dolly Ki Doli",
    "Hawaizaada",
    "Khamoshiyan",
    "Rahasya",
    "Jai Jawaan Jai Kisaan",
    "Shamitabh",
    "Roy",
    "Badlapur",
    "Crazy Cukkad Family",
    "Take It Easy",
    "Qissa",
    "Ab Tak Chhappan 2",
    "Dum Laga Ke Haisha",
    "Dirty Politics",
    "MSG: The Messenger",
    "Badmashiyaan",
    "Coffee Bloom",
    "Hey Bro",
    "NH10",
    "Hunterrr",
    "Detective Byomkesh Bakshy!",
    "Luckhnowi Ishq",
    "Court",
    "Margarita with a Straw",
    "Ek Paheli Leela",
    "Barkhaa",
    "Mr. X",
    "NH-8 Road to Nidhivan",
    "Dilliwali Zaalim Girlfriend",
    "Dharam Sankat Mein",
    "Kaagaz Ke Fools",
    "Gabbar Is Back",
    "Kuch Kuch Locha Hai",
    "Piku",
    "Bombay Velvet",
    "Tanu Weds Manu: Returns",
    "I Love Desi",
    "Dil Dhadakne Do",
    "Welcome 2 Karachi",
    "P Se PM Tak",
    "Mere Genie Uncle",
    "Hamari Adhuri Kahani",
    "Miss Tanakpur Haazir Ho",
    "Uvaa",
    "Ishq Ke Parindey",
    "Ishqedarriyaan",
    "Sabki Bajegi Band",
    "Masaan",
    "Guddu Rangeela",
    "Bezubaan Ishq",
    "Aisa Yeh Jahaan",
    "Second Hand Husband",
    "I Love NY",
    "Main Hoon Part-Time Killer",
    "Kaun Kitne Paani Mein",
    "Drishyam",
    "Bangistan",
    "All Is Well",
    "Brothers",
    "Gour Hari Dastaan",
    "Manjhi – The Mountain Man",
    "Thoda Lutf Thoda Ishq",
    "Phantom",
    "Hero",
    "Sorry Daddy",
    "Talvar",
    "Katti Batti",
    "Meeruthiya Gangsters",
    "MSG-2 The Messenger",
    "Calendar Girls",
    "Mumbhaii - The Gangster",
    "Bhaag Johnny",
    "Jazbaa",
    "Bumper Draw",
    "Chinar Daastaan-E-Ishq",
    "Kis Kisko Pyaar Karoon",
    "Pyaar Ka Punchnama 2",
    "Wedding Pullav",
    "Shaandaar",
    "Titli",
    "Main Aur Charles",
    "Guddu Ki Gun",
    "Charlie Kay Chakkar Mein",
    "Yaara Silly Silly",
    "Four Pillars of Basement",
    "X: Past Is Present",
    "Angry Indian Goddesses",
    "Tamasha",
    "Hate Story 3",
    "Kajarya",
    "The Silent Heroes",
    "Mr Joe B. Carvalho",
    "Once Upon a Time in Bihar",
    "Ranbanka",
    "Sholay",
    "Dedh Ishqiya",
    "Karle Pyaar Karle",
    "Yaariyan",
    "Miss Lovely",
    "Om-Dar-B-Dar",
    "Paranthe Wali Gali",
    "Strings of Passion",
    "Gunday",
    "Jai Ho",
    "Hasee Toh Phasee",
    "Heartless",
    "Ya Rab",
    "Darr @ the Mall",
    "One by Two",
    "Babloo Happy Hai",
    "Highway",
    "Gulabi Gang",
    "Shaadi Ke Side Effects",
    "Gulaab Gang",
    "Queen",
    "Bewakoofiyaan",
    "Neighbours: They Are Vampires",
    "Total Siyapaa",
    "Dee Saturday Night",
    "Karar: The Deal",
    "Lakshmi",
    "Ragini MMS 2",
    "Dishkiyaoon",
    "Ankhon Dekhi",
    "Gang of Ghosts",
    "Pyar Ka Live Show",
    "Anuradha",
    "W",
    "O Teri",
    "Honour Killing",
    "2 States",
    "Jal",
    "Bhoothnath Returns",
    "Main Tera Hero",
    "Lucky Kabootar",
    "Station",
    "Youngistaan",
    "Samrat & Co.",
    "Purani Jeans",
    "Kya Dilli Kya Lahore",
    "Koyelaanchal",
    "Manjunath",
    "Dekh Tamasha Dekh",
    "Mastram",
    "The Xposé",
    "Children of War",
    "M3 - Midsummer Midnight Mumbai",
    "Hawaa Hawaai",
    "Kahin Hai Mera Pyar",
    "Kuku Mathur Ki Jhand Ho Gayi",
    "Heropanti",
    "CityLights",
    "Filmistaan",
    "Revolver Rani",
    "Kaanchi: The Unbreakable",
    "Machhli Jal Ki Rani Hai",
    "Khwaabb",
    "Yeh Hai Bakrapur",
    "Ek Villain",
    "Bobby Jasoos",
    "Humshakals",
    "Humpty Sharma Ki Dulhania",
    "Hate Story 2",
    "Lekar Hum Deewana Dil",
    "Riyasat",
    "Amit Sahni Ki List",
    "Holiday: A Soldier Is Never Off Duty",
    "Fugly",
    "Bazaar E Husn",
    "Pizza",
    "Entertainment",
    "Singham Returns",
    "Mardaani",
    "Raja Natwarlal",
    "Mary Kom",
    "Creature 3D",
    "Finding Fanny",
    "Khoobsurat",
    "3 A.M.",
    "Kick",
    "Mad About Dance",
    "Mumbhai Connection",
    "Life Is Beautiful",
    "Desi Kattey",
    "Haider",
    "Bang Bang!",
    "Spark",
    "Daawat-e-Ishq",
    "Balwinder Singh Famous Ho Gaya",
    "Jigariyaa",
    "Tamanchey",
    "Mumbai 125 KM",
    "Meinu Ek Ladki Chaahiye",
    "Chaarfutiya Chhokare",
    "Sonali Cable",
    "Happy New Year",
    "Super Nani",
    "Ekkees Toppon Ki Salaami",
    "Rang Rasiya",
    "Fireflies",
    "The Shaukeens",
    "Roar: Tigers of the Sundarbans",
    "A Decent Arrangement",
    "Gollu Aur Pappu",
    "Titoo MBA",
    "Kill Dil",
    "Ungli",
    "Happy Ending",
    "Zed Plus",
    "Zid",
    "Action Jackson",
    "Bhopal: A Prayer for Rain",
    "Mumbai Delhi Mumbai",
    "Badlapur Boys",
    "6-5=2",
    "Main Aur Mr. Riight",
    "Ugly",
    "PK",
    "Life Mein Twist Hai",
    "Dehraadun Diary",
    "Matru Ki Bijlee Ka Mandola",
    "Sulemani Keeda",
    "Meri Shadi Karao",
    "Inkaar",
    "Thriller film",
    "Gangoobai",
    "Akaash Vani",
    "Main Krishna Hoon",
    "Race 2",
    "Bandook",
    "Listen... Amaya",
    "Special 26",
    "Murder 3",
    "Zila Ghaziabad",
    "Kai Po Che!",
    "Bloody Isshq",
    "Saare Jahaan Se Mehnga",
    "3G",
    "Mere Dad Ki Maruti",
    "Jolly LLB",
    "Saheb Biwi Aur Gangster Returns",
    "Mai",
    "Vishwaroopam",
    "Rangrezz",
    "Aashiqui 2",
    "Ek Thi Daayan",
    "Himmatwala",
    "Nautanki Saala!",
    "Jayantabhai Ki Luv Story",
    "Shree",
    "Commando: A One Man Army",
    "Bombay Talkies",
    "Go Goa Gone",
    "Gippi",
    "Aurangzeb",
    "Ishkq in Paris",
    "Zindagi 50-50",
    "Yeh Jawaani Hai Deewani",
    "Fukrey",
    "Chhota Bheem and the Throne of Bali",
    "Raanjhanaa",
    "Ankur Arora Murder Case",
    "Shortcut Romeo",
    "Ghanchakkar",
    "I Don't Luv U",
    "Hum Hai Raahi Car Ke",
    "Boyss Toh Boyss Hain",
    "Policegiri",
    "Bhaag Milkha Bhaag",
    "Sixteen",
    "B.A. Pass",
    "Enemmy",
    "Issaq",
    "Bajatey Raho",
    "Luv U Soniyo",
    "Nasha",
    "Chor Chor Super Chor",
    "Calapor",
    "Love in Bombay",
    "D-Day",
    "Siddharth",
    "Once Upon ay Time in Mumbai Dobaara!",
    "Madras Cafe",
    "Satyagraha",
    "Shuddh Desi Romance",
    "Ramaiya Vastavaiya",
    "Chennai Express",
    "Grand Masti",
    "John Day",
    "Horror Story",
    "Phata Poster Nikhla Hero",
    "Ship of Theseus",
    "The Lunchbox",
    "Warning",
    "Crime film",
    "Baat Bann Gayi",
    "Boss",
    "Shahid",
    "Mickey Virus",
    "Satya 2",
    "Rajjo",
    "Maazii",
    "Dilli Gang",
    "Sooper Se Ooper",
    "Prague",
    "Wake Up India",
    "Super Model",
    "Gori Tere Pyaar Mein",
    "What the Fish",
    "Jackpot",
    "Table No. 21",
    "Bullett Raja",
    "Dhoom 3",
    "Chashme Baddoor",
    "Lootera",
    "War Chhod Na Yaar",
    "Chaalis Chauraasi",
    "Ghost",
    "Sadda Adda",
    "Singh Saab the Great",
    "Goliyon Ki Raasleela Ram-Leela",
    "Agneepath",
    "Ek Main Aur Ekk Tu",
    "Ekk Deewana Tha",
    "?: A Question Mark",
    "Jodi Breakers",
    "Tere Naal Love Ho Gaya",
    "Staying Alive",
    "Will You Marry Me?",
    "Paan Singh Tomar",
    "Kahaani",
    "Zindagi Tere Naam",
    "Agent Vinod",
    "Blood Money",
    "Bumboo",
    "Valentine's Night",
    "Married 2 America",
    "Chaar Din Ki Chandni",
    "Say Yes to Love",
    "Bittoo Boss",
    "Vicky Donor",
    "Hate Story",
    "Tezz",
    "Ab Hoga Dharna Unlimited",
    "Dangerous Ishhq",
    "Ishaqzaade",
    "Department",
    "Horror film",
    "Fatso!",
    "Arjun: The Warrior Prince",
    "Animation",
    "Life Ki Toh Lag Gayi",
    "Shanghai",
    "Ferrari Ki Sawaari",
    "Teri Meri Kahaani",
    "Mr. Bhatti on Chutti",
    "Yeh Khula Aasmaan",
    "Rakhtbeej",
    "Gangs of Wasseypur",
    "Cocktail",
    "Gattu",
    "Kyaa Super Kool Hain Hum",
    "Drama",
    "Maximum",
    "Paanch Ghantey Mien Paanch Crore",
    "Ek Tha Tiger",
    "Gangs of Wasseypur – Part 2",
    "Challo Driver",
    "Shirin Farhad Ki Toh Nikal Padi",
    "Joker",
    "Aalaap",
    "Mere Dost Picture Abhi Baki Hai",
    "Krishna Aur Kans",
    "From Sydney with Love",
    "Comedy",
    "Jalpari: The Desert Mermaid",
    "Barfi!",
    "Heroine",
    "Kamaal Dhamaal Malamaal",
    "Chal Pichchur Banate Hain",
    "Kismat Love Paisa Dilli",
    "Jeena Hai Toh Thok Daal",
    "OMG – Oh My God!",
    "Aiyyaa",
    "Chittagong",
    "Bhoot Returns",
    "Delhi Safari",
    "Chakravyuh",
    "Student of the Year",
    "Ajab Gazabb Love",
    "Rush",
    "1920: The Evil Returns",
    "Sons of Ram",
    "Ata Pata Laapata",
    "Jab Tak Hai Jaan",
    "Talaash: The Answer Lies Within",
    "Login",
    "Son of Sardaar",
    "Cigarette Ki Tarah",
    "Dabangg 2",
    "Players",
    "Housefull 2",
    "Bol Bachchan",
    "English Vinglish",
    "Impatient Vivek",
    "Yamla Pagla Deewana",
    "Mumbai Mast Kallander",
    "Dhobi Ghat",
    "Turning 30",
    "Hostel",
    "Dil Toh Baccha Hai Ji",
    "United Six",
    "Utt Pataang",
    "Patiala House",
    "7 Khoon Maaf",
    "Tanu Weds Manu",
    "F.A.L.T.U",
    "Memories in March",
    "Thank You",
    "Angel",
    "Happy Husbands",
    "Teen Thay Bhai",
    "Dum Maaro Dum",
    "Shor in the City",
    "Zokkomon",
    "Chalo Dilli",
    "Aashiqui.in",
    "Satrangee Parachute",
    "Monica",
    "I Am",
    "Naughty @ 40",
    "Haunted – 3D",
    "Love U...Mr. Kalakaar!",
    "Ragini MMS",
    "Stanley Ka Dabba",
    "Shagird",
    "404",
    "Shaitan",
    "Pyaar Ka Punchnama",
    "Bheja Fry 2",
    "Always Kabhi Kabhi",
    "Double Dhamaal",
    "Bbuddah... Hoga Terra Baap",
    "Delhi Belly",
    "Murder 2",
    "Chillar Party",
    "Zindagi Na Milegi Dobara",
    "Dear Friend Hitler",
    "I Am Kalam",
    "Bin Bulaye Baraati",
    "Kucch Luv Jaisaa",
    "Singham",
    "Khap",
    "Bubble Gum",
    "Shabri",
    "Phhir",
    "Aarakshan",
    "Chatur Singh Two Star",
    "Sahi Dhandhe Galat Bande",
    "Bodyguard",
    "Yeh Dooriyan",
    "Not a Love Story",
    "Hum Tum Shabana",
    "Mummy Punjabi",
    "Mere Brother Ki Dulhan",
    "Mausam",
    "U R My Jaan",
    "Force",
    "Saheb Biwi Aur Gangster",
    "Tere Mere Phere",
    "Breakaway",
    "Chargesheet",
    "Love Breakups Zindagi",
    "Mujhse Fraaandship Karoge",
    "Aazaan",
    "Ra.One",
    "Rockstar",
    "Miley Naa Miley Hum",
    "Tell Me O Kkhuda",
    "Damadamm!",
    "Ladies vs Ricky Bahl",
    "Desi Boyz",
    "Game",
    "No One Killed Jessica",
    "Rascals",
    "The Dirty Picture",
    "Pyaar Impossible!",
    "Chance Pe Dance",
    "My Friend Pinto",
    "Shakal Pe Mat Ja",
    "Veer",
    "Striker",
    "Rann",
    "Ishqiya",
    "Road to Sangam",
    "Jo Hum Chahein",
    "Click",
    "Toh Baat Pakki!",
    "My Name Is Khan",
    "Teen Patti",
    "Karthik Calling Karthik",
    "Don 2",
    "Rokkk",
    "Aakhari Decision",
    "Right Yaaa Wrong",
    "Sukhmani: Hope for Life",
    "Thanks Maa",
    "Na Ghar Ke Na Ghaat Ke",
    "Trump Card",
    "Shaapit",
    "Hum Tum Aur Ghost",
    "My Friend Ganesha 3",
    "Well Done Abba",
    "Tum Milo Toh Sahi",
    "Jaane Kahan Se Aayi Hai",
    "Prem Kaa Game",
    "Sadiyaan",
    "The Japanese Wife",
    "Paathshaala",
    "Phoonk 2",
    "Lahore",
    "Apartment",
    "City of Gold",
    "Chase",
    "Housefull",
    "Mittal v/s Mittal",
    "It's a Wonderful Afterlife",
    "Prince",
    "Raavan",
    "Bumm Bumm Bole",
    "Kushti",
    "Kites",
    "Love Sex Aur Dhokha",
    "Milenge Milenge",
    "Ek Second... Jo Zindagi Badal De?",
    "Mr. Singh Mrs. Mehta",
    "Lamhaa",
    "Khatta Meetha",
    "Tere Bin Laden",
    "Udaan",
    "Once Upon a Time in Mumbaai",
    "Help",
    "Peepli Live",
    "Lafangey Parindey",
    "Hello Darling",
    "Antardwand",
    "Aashayein",
    "Soch Lo",
    "Mallika",
    "Dabangg",
    "Khichdi: The Movie",
    "Red Alert: The War Within",
    "Life Express",
    "The Film Emotional Atyachar",
    "Hisss",
    "Crook",
    "Do Dooni Chaar",
    "Aakrosh",
    "Ramayana: The Epic",
    "Knock Out",
    "Jhootha Hi Sahi",
    "Nakshatra",
    "Guzaarish",
    "Shahrukh Bola 'Khoobsurat Hai Tu'",
    "Diwangi Ne Had Kar Di",
    "Allah Ke Banday",
    "Break Ke Baad",
    "Khuda Kasam",
    "Phas Gaye Re Obama",
    "Malik Ek",
    "A Flat",
    "No Problem",
    "Band Baaja Baaraat",
    "Kaalo",
    "332 Mumbai to India",
    "Mirch",
    "Tees Maar Khan",
    "Payback",
    "Isi Life Mein",
    "Toonpur Ka Super Hero",
    "Tera Kya Hoga Johnny",
    "Ramaa: The Saviour",
    "I Hate Luv Storys",
    "Ada... A Way of Life",
    "Dulha Mil Gaya",
    "Anjaana Anjaani",
    "Dunno Y... Na Jaane Kyon",
    "Pankh",
    "Action Replayy"
]

insta_followers = [
    {
        'name': 'Instagram',
        'follower_count': 346,
        'description': 'Social media platform',
        'country': 'United States'
    },
    {
        'name': 'Cristiano Ronaldo',
        'follower_count': 215,
        'description': 'Footballer',
        'country': 'Portugal'
    },
    {
        'name': 'Ariana Grande',
        'follower_count': 183,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Dwayne Johnson',
        'follower_count': 181,
        'description': 'Actor and professional wrestler',
        'country': 'United States'
    },
    {
        'name': 'Selena Gomez',
        'follower_count': 174,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Kylie Jenner',
        'follower_count': 172,
        'description': 'Reality TV personality and businesswoman and Self-Made Billionaire',
        'country': 'United States'
    },
    {
        'name': 'Kim Kardashian',
        'follower_count': 167,
        'description': 'Reality TV personality and businesswoman',
        'country': 'United States'
    },
    {
        'name': 'Lionel Messi',
        'follower_count': 149,
        'description': 'Footballer',
        'country': 'Argentina'
    },
    {
        'name': 'Beyoncé',
        'follower_count': 145,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Neymar',
        'follower_count': 138,
        'description': 'Footballer',
        'country': 'Brasil'
    },
    {
        'name': 'National Geographic',
        'follower_count': 135,
        'description': 'Magazine',
        'country': 'United States'
    },
    {
        'name': 'Justin Bieber',
        'follower_count': 133,
        'description': 'Musician',
        'country': 'Canada'
    },
    {
        'name': 'Taylor Swift',
        'follower_count': 131,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Kendall Jenner',
        'follower_count': 127,
        'description': 'Reality TV personality and Model',
        'country': 'United States'
    },
    {
        'name': 'Jennifer Lopez',
        'follower_count': 119,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Nicki Minaj',
        'follower_count': 113,
        'description': 'Musician',
        'country': 'Trinidad and Tobago'
    },
    {
        'name': 'Nike',
        'follower_count': 109,
        'description': 'Sportswear multinational',
        'country': 'United States'
    },
    {
        'name': 'Khloé Kardashian',
        'follower_count': 108,
        'description': 'Reality TV personality and businesswoman',
        'country': 'United States'
    },
    {
        'name': 'Miley Cyrus',
        'follower_count': 107,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Katy Perry',
        'follower_count': 94,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Kourtney Kardashian',
        'follower_count': 90,
        'description': 'Reality TV personality',
        'country': 'United States'
    },
    {
        'name': 'Kevin Hart',
        'follower_count': 89,
        'description': 'Comedian and actor',
        'country': 'United States'
    },
    {
        'name': 'Ellen DeGeneres',
        'follower_count': 87,
        'description': 'Comedian',
        'country': 'United States'
    },
    {
        'name': 'Real Madrid CF',
        'follower_count': 86,
        'description': 'Football club',
        'country': 'Spain'
    },
    {
        'name': 'FC Barcelona',
        'follower_count': 85,
        'description': 'Football club',
        'country': 'Spain'
    },
    {
        'name': 'Rihanna',
        'follower_count': 81,
        'description': 'Musician and businesswoman',
        'country': 'Barbados'
    },
    {
        'name': 'Demi Lovato',
        'follower_count': 80,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': "Victoria's Secret",
        'follower_count': 69,
        'description': 'Lingerie brand',
        'country': 'United States'
    },
    {
        'name': 'Zendaya',
        'follower_count': 68,
        'description': 'Actress and musician',
        'country': 'United States'
    },
    {
        'name': 'Shakira',
        'follower_count': 66,
        'description': 'Musician',
        'country': 'Colombia'
    },
    {
        'name': 'Drake',
        'follower_count': 65,
        'description': 'Musician',
        'country': 'Canada'
    },
    {
        'name': 'Chris Brown',
        'follower_count': 64,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'LeBron James',
        'follower_count': 63,
        'description': 'Basketball player',
        'country': 'United States'
    },
    {
        'name': 'Vin Diesel',
        'follower_count': 62,
        'description': 'Actor',
        'country': 'United States'
    },
    {
        'name': 'Cardi B',
        'follower_count': 67,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'David Beckham',
        'follower_count': 82,
        'description': 'Footballer',
        'country': 'United Kingdom'
    },
    {
        'name': 'Billie Eilish',
        'follower_count': 61,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Justin Timberlake',
        'follower_count': 59,
        'description': 'Musician and actor',
        'country': 'United States'
    },
    {
        'name': 'UEFA Champions League',
        'follower_count': 58,
        'description': 'Club football competition',
        'country': 'Europe'
    },
    {
        'name': 'NASA',
        'follower_count': 56,
        'description': 'Space agency',
        'country': 'United States'
    },
    {
        'name': 'Emma Watson',
        'follower_count': 56,
        'description': 'Actress',
        'country': 'United Kingdom'
    },
    {
        'name': 'Shawn Mendes',
        'follower_count': 57,
        'description': 'Musician',
        'country': 'Canada'
    },
    {
        'name': 'Virat Kohli',
        'follower_count': 55,
        'description': 'Cricketer',
        'country': 'India'
    },
    {
        'name': 'Gigi Hadid',
        'follower_count': 54,
        'description': 'Model',
        'country': 'United States'
    },
    {
        'name': 'Priyanka Chopra Jonas',
        'follower_count': 53,
        'description': 'Actress and musician',
        'country': 'India'
    },
    {
        'name': '9GAG',
        'follower_count': 52,
        'description': 'Social media platform',
        'country': 'China'
    },
    {
        'name': 'Ronaldinho',
        'follower_count': 51,
        'description': 'Footballer',
        'country': 'Brasil'
    },
    {
        'name': 'Maluma',
        'follower_count': 50,
        'description': 'Musician',
        'country': 'Colombia'
    },
    {
        'name': 'Camila Cabello',
        'follower_count': 49,
        'description': 'Musician',
        'country': 'Cuba'
    },
    {
        'name': 'NBA',
        'follower_count': 47,
        'description': 'Club Basketball Competition',
        'country': 'United States'
    }
]

question_data = [
    {"category": "Entertainment: Film",
     "type": "multiple",
     "difficulty": "medium",
     "question": "What was Marilyn Monroe`s character's first name in the film :Some Like It Hot:?",
     "correct_answer": "Sugar",
     "incorrect_answers": ["Honey", "Caramel", "Candy"]
     },
    {"category": "Geography",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Greenland is almost as big as Africa.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "History",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The sum of all the numbers on a roulette wheel is 666.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Geography",
     "type": "boolean",
     "difficulty": "medium",
     "question": "There exists an island named :Java:.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Entertainment: Video Games",
     "type": "multiple",
     "difficulty": "easy",
     "question": "How many differently shaped Tetris pieces are there?",
     "correct_answer": "7",
     "incorrect_answers": ["5", "6", "8"]
     },
    {"category": "Science: Computers",
     "type": "multiple",
     "difficulty": "easy",
     "question": "On Twitter, what was the original character limit for a Tweet?",
     "correct_answer": "140",
     "incorrect_answers": ["120", "160", "100"]
     },
    {"category": "Entertainment: Video Games",
     "type": "multiple",
     "difficulty": "medium",
     "question": "Which of these is the only fighter in the game :Super Smash Bros. Melee: capable of dealing damage "
                 "with their taunt animation?",
     "correct_answer": "Luigi",
     "incorrect_answers": ["Mr. GameWatch", "Jigglypuff", "Pichu"]
     },
    {"category": "Entertainment: Video Games",
     "type": "multiple",
     "difficulty": "hard",
     "question": "What Pokemon's Base Stat Total does not change when it evolves?",
     "correct_answer": "Scyther",
     "incorrect_answers": ["Pikachu", "Sneasel", "Larvesta"]
     },
    {"category": "General Knowledge",
     "type": "multiple",
     "difficulty": "easy",
     "question": "What kind of aircraft was developed by Igor Sikorsky in the United States in 1942?",
     "correct_answer": "Helicopter",
     "incorrect_answers": ["Stealth Blimp", "Jet", "Space Capsule"]
     }
]

blackjack_cards = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10, 11]

coffee_menu = {
    "espresso": {
        "ingredients": {
            "water": 50,
            "coffee": 18,
        },
        "cost": 1.5,
    },
    "latte": {
        "ingredients": {
            "water": 200,
            "milk": 150,
            "coffee": 24,
        },
        "cost": 2.5,
    },
    "cappuccino": {
        "ingredients": {
            "water": 250,
            "milk": 100,
            "coffee": 24,
        },
        "cost": 3.0,
    }
}

coffee_resources = {
    "water": 300,
    "milk": 200,
    "coffee": 100,
}
